// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto

package com.deloitte.product.stubs;

public final class ProductServiceOuterClass {
  private ProductServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ProductService.proto\"4\n\007Product\022\014\n\004nam" +
      "e\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\r\n\005price\030\003 \001(\005\")\n\016" +
      "ProductRequest\022\027\n\005input\030\001 \001(\0132\010.Product\"" +
      "+\n\017ProductResponse\022\030\n\006output\030\001 \001(\0132\010.Pro" +
      "duct2M\n\016ProductService\022;\n\024searchProductC" +
      "atalog\022\017.ProductRequest\032\020.ProductRespons" +
      "e0\001B\036\n\032com.deloitte.product.stubsP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Product_descriptor,
        new java.lang.String[] { "Name", "Type", "Price", });
    internal_static_ProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductRequest_descriptor,
        new java.lang.String[] { "Input", });
    internal_static_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductResponse_descriptor,
        new java.lang.String[] { "Output", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
