// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto

package com.deloitte.product.stubs;

public interface ProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Product output = 1;</code>
   */
  boolean hasOutput();
  /**
   * <code>.Product output = 1;</code>
   */
  com.deloitte.product.stubs.Product getOutput();
  /**
   * <code>.Product output = 1;</code>
   */
  com.deloitte.product.stubs.ProductOrBuilder getOutputOrBuilder();
}
