// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto

package com.deloitte.product.stubs;

public interface ProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Product input = 1;</code>
   */
  boolean hasInput();
  /**
   * <code>.Product input = 1;</code>
   */
  com.deloitte.product.stubs.Product getInput();
  /**
   * <code>.Product input = 1;</code>
   */
  com.deloitte.product.stubs.ProductOrBuilder getInputOrBuilder();
}
